USE [master]
GO
/****** Object:  Database [PruebaXamarin]    Script Date: 20/06/2023 11:54:02 p. m. ******/
CREATE DATABASE [PruebaXamarin]
GO
ALTER DATABASE [PruebaXamarin] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PruebaXamarin].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PruebaXamarin] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PruebaXamarin] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PruebaXamarin] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PruebaXamarin] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PruebaXamarin] SET ARITHABORT OFF 
GO
ALTER DATABASE [PruebaXamarin] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PruebaXamarin] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PruebaXamarin] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PruebaXamarin] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PruebaXamarin] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PruebaXamarin] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PruebaXamarin] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PruebaXamarin] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PruebaXamarin] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PruebaXamarin] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PruebaXamarin] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PruebaXamarin] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PruebaXamarin] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PruebaXamarin] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PruebaXamarin] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PruebaXamarin] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PruebaXamarin] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PruebaXamarin] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PruebaXamarin] SET  MULTI_USER 
GO
ALTER DATABASE [PruebaXamarin] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PruebaXamarin] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PruebaXamarin] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PruebaXamarin] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PruebaXamarin] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PruebaXamarin] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [PruebaXamarin] SET QUERY_STORE = ON
GO
ALTER DATABASE [PruebaXamarin] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [PruebaXamarin]
GO
/****** Object:  Table [dbo].[ListadoEstudiantes]    Script Date: 20/06/2023 11:54:03 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ListadoEstudiantes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](30) NOT NULL,
	[Edad] [int] NOT NULL,
	[Sexo] [varchar](10) NOT NULL,
	[Escolaridad] [varchar](50) NOT NULL,
 CONSTRAINT [PK_ListadoEstudiantes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [PruebaXamarin] SET  READ_WRITE 
GO
